# .github/workflows/deploy.yml
name: Build and Push to Azure

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # GitHub ki VM ko Azure se login karwaya
    - name: Azure Container Registry Login
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    # YAHAN LIKHA HAI KI KON SI IMAGE BANANI HAI AUR PUSH KARNI HAI!
    - name: Build and Push Backend Image
      run: |
        # 1. Image ko build karte waqt naam aur tag diya jata hai (-t matlab Tag/Name)
        docker build -t container-registry-name.azurecr.io/backend-api:latest -f backend/Dockerfile .

        # 2. Phir isi exact naam ko push kiya jata hai
        docker push container-registry-name.azurecr.io/backend-api:latest       




# container-registry-name.azurecr.io=>>>>> ye exact wo h jo hmne cloud p registry ka name create kiya h
# vipiragregistry.azurecr.io / backend-api : latest
# └───────────┬────────────┘   └────┬──────┘   └─┬──┘
#             │                     │            │
#  1. Registry Address      2. Image Name    3. Tag (Version)
#  Aap Apni Marzi Se Aise Naam Aur Tag Rakh Sakte Hain:
#  Example 1 (Simple): vipiragregistry.azurecr.io/my-backend:latest(Naam badal kar my-backend kar diya, tag latest hi rakha)
#  Example 2 (Project wise): vipiragregistry.azurecr.io/rag-pipeline:v1.0(Naam rag-pipeline rakh diya aur tag mein version number :v1.0 de diya)
#  Example 3 (Testing ke liye): vipiragregistry.azurecr.io/test-app:beta(Naam test-app aur tag :beta de diya)




